# Generated by Django 4.0.2 on 2022-02-27 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consigliflix', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
    ]
