# Generated by Django 4.0.2 on 2022-02-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consigliflix', '0002_alter_review_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
        migrations.AddField(
            model_name='movie',
            name='platform',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(default=None, null=True),
        ),
    ]
