# Generated by Django 4.0.2 on 2022-02-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consigliflix', '0003_remove_movie_year_movie_platform_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
