# Generated by Django 4.0.2 on 2022-02-28 21:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consigliflix', '0004_movie_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingPlatforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'streaming_platform',
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='platform',
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.CreateModel(
            name='MoviesSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consigliflix.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movies_seen',
            },
        ),
        migrations.CreateModel(
            name='MoviePlatforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consigliflix.movie')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consigliflix.streamingplatforms')),
            ],
            options={
                'db_table': 'movie_platforms',
            },
        ),
    ]
