# Generated by Django 4.0.2 on 2022-03-01 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consigliflix', '0005_streamingplatforms_remove_movie_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieplatforms',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability', to='consigliflix.movie'),
        ),
        migrations.AlterField(
            model_name='movieplatforms',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue', to='consigliflix.streamingplatforms'),
        ),
        migrations.AlterField(
            model_name='moviesseen',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='consigliflix.movie'),
        ),
        migrations.AlterField(
            model_name='moviesseen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='consigliflix.movie'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
